version: "1"
name: metrics
services:
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - prometheus:/etc/data/prometheus

  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=12345
    volumes:
      - grafana:/etc/data/grafana

volumes:
  grafana:
  prometheus: