version: 0.0.1
name: app_estate
services:
  app_estate:
    container_name: app_estate
    image: estate_image
    restart: on-failure
    environment:
      - ENV=prod
      - PORT=3004
      - DB_USER=admin
      - DB_PASSWORD=1787
      - DB_NAME=estate
      - DB_PORT=4000
      - DB_HOST=postgres_estate
      - BROKER_ADDR=localhost:29092
      - TOPIC_METRICS=metrics
    ports:
      - 3004:3004