basePath: /v1
definitions:
  models.CancelMeetingParameter:
    properties:
      id:
        type: string
      visitorPhone:
        type: string
    type: object
  models.Estate:
    properties:
      city:
        type: string
      country:
        type: string
      description:
        type: string
      floor:
        type: integer
      id:
        type: string
      images:
        items:
          type: string
        type: array
      mainImage:
        type: string
      price:
        type: number
      square:
        type: number
      street:
        type: string
      title:
        type: string
    type: object
  models.EstateInfo:
    properties:
      city:
        type: string
      country:
        type: string
      id:
        type: string
      mainImage:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  models.Meeting:
    properties:
      date:
        type: string
      estateID:
        type: string
      visitorPhone:
        type: string
    type: object
info:
  contact: {}
  description: Real Estate app gateway
  title: Real Estate
  version: "1.0"
paths:
  /estate/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: estate id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: DeleteEstate
      tags:
      - estate
  /estate/info/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: estate id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Estate'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetInfo
      tags:
      - estate
  /estate/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: country
        in: query
        name: country
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      - description: city
        in: query
        name: city
        type: string
      - description: floor
        in: path
        name: floor
        type: integer
      - description: square
        in: path
        name: square
        type: integer
      - description: min price
        in: path
        name: minPrice
        type: integer
      - description: max price
        in: path
        name: maxPrice
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EstateInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetList
      tags:
      - estate
  /estate/new:
    post:
      consumes:
      - application/json
      parameters:
      - description: estate
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Estate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: CreateEstate
      tags:
      - estate
  /meetings/arrange:
    post:
      consumes:
      - application/json
      parameters:
      - description: meeting info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Meeting'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: ArrangeMeeting
      tags:
      - meetings
  /meetings/available:
    get:
      consumes:
      - application/json
      parameters:
      - description: estate id
        in: query
        name: estateID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetAvailableTime
      tags:
      - meetings
  /meetings/cancel:
    put:
      consumes:
      - application/json
      parameters:
      - description: meeting info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CancelMeetingParameter'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: CancelMeeting
      tags:
      - meetings
  /meetings/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: estate id
        in: query
        name: estateID
        type: string
      - description: phone number id
        in: query
        name: phoneNumber
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Meeting'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetMeetings
      tags:
      - meetings
swagger: "2.0"
