name: Main on push
on:
  push:
    branches:
      - main
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ estate, metrics, gateway, meetings ]
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: tidy
        working-directory: ${{ matrix.dir }}
        run: go mod tidy

      - name: linter
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ matrix.dir }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linter
    strategy:
      matrix:
        dir: [ estate, metrics ]
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: tidy
        working-directory: ${{ matrix.dir }}
        run: go mod tidy

      - name: testing
        working-directory: ${{ matrix.dir }}
        run: go test -v ./...