name: Meetings on push
on:
  push:
    branches:
      - meetings
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: testing
        working-directory: meetings
        run: go test -v ./...

  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: linter
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: meetings