name: Meetings on push
on:
  push:
    branches:
      - meetings
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ meetings ]
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: tidy
        run: go mod tidy
        working-directory: ${{ matrix.dir }}

      - name: linter
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: ${{ matrix.dir }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linter
    strategy:
      matrix:
        dir: [ meetings ]
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v3

      - name: tidy
        run: go mod tidy
        working-directory: ${{ matrix.dir }}

      - name: testing
        working-directory: ${{ matrix.dir }}
        run: go test -v ./...
